(function () {
  'use strict';
  angular.module('autogeneratedForm').factory('contractSrvc', ['$http', function($http, $location) {

    function appendTransform(defaults, transform) {

      // We can't guarantee that the default transformation is an array
      defaults = angular.isArray(defaults) ? defaults : [defaults];

      // Append the new transformation to the defaults
      return defaults.concat(transform);
    }

    function getUserParam() {
      var userId = getUrlParam('user');
      if (userId) {
        return { 'user': userId };
      }
      return {};
    }

    /**
     * Extract the param value from a URL query
     * e.g. if param = "id", it extracts the id value in the following cases:
     *  1. http://localhost/bonita/portal/resource/process/ProcName/1.0/content/?id=8880000
     *  2. http://localhost/bonita/portal/resource/process/ProcName/1.0/content/?param=value&id=8880000&locale=en
     *  3. http://localhost/bonita/portal/resource/process/ProcName/1.0/content/?param=value&id=8880000&locale=en#hash=value
     * @returns {id}
     */
    function getUrlParam(param) {
      var paramValue = $location.absUrl().match('[//?&]' + param + '=([^&#]*)($|[&#])');
      if (paramValue) {
        return paramValue[1];
      }
      return '';
    }

    return {
      fetchContract: function (taskId) {
        // fetch contract from server
        return $http({
          url: '../API/bpm/userTask/' + taskId + '/contract',
          method: 'GET'
        });
      },
      executeTask: function(taskId, dataToSend) {
        // submit data to execute task on server
        return $http({
          url: '../API/bpm/userTask/' + taskId + '/execution',
          method: 'POST',
          data: dataToSend,
          params: getUserParam(),
          transformRequest: appendTransform($http.defaults.transformRequest, function(value, headers) {
            console.log('Request:', value);
            return value;
          })
        });
      }
    };
  }]);
})();
